// ============================================
// Q&A BANK — Descriptive (likhne wale) sawal
// Har subject mein bohat se answer questions
// AI inhe grade karta hai
// ============================================

export interface QAQuestion {
  q: string;
  hint: string;
  idealAnswer: string;
}

export const QA_BANK: Record<string, QAQuestion[]> = {
  Physics: [
    { q: "State Ohm's Law and describe two cases where it fails (Non-Ohmic conductors).", hint: "V = IR at constant temperature. Fails in diodes and filament lamps.", idealAnswer: "Ohm's Law states that the current through a conductor is directly proportional to the voltage across it, provided temperature stays constant (V = IR). It fails in non-ohmic devices like semiconductor diodes (non-linear, directional conduction) and filament lamps (resistance rises with heat)." },
    { q: "Define Newton's three laws of motion with one example each.", hint: "Inertia, F=ma, action-reaction.", idealAnswer: "1) First Law (Inertia): A body stays at rest or in uniform motion unless a force acts — e.g., a book on a table. 2) Second Law: F = ma — pushing a heavier cart needs more force. 3) Third Law: Every action has an equal and opposite reaction — a rocket pushes gas down and moves up." },
    { q: "Differentiate between scalar and vector quantities with examples.", hint: "Magnitude only vs magnitude + direction.", idealAnswer: "Scalars have only magnitude — e.g., mass, time, speed, temperature. Vectors have both magnitude and direction — e.g., velocity, displacement, force, acceleration. Vectors are shown by arrows indicating direction." },
    { q: "What is gravitation? State Newton's law of universal gravitation.", hint: "Attraction between masses, F = Gm₁m₂/r².", idealAnswer: "Gravitation is the force of attraction between any two masses in the universe. Newton's law states this force is directly proportional to the product of their masses and inversely proportional to the square of the distance between them: F = Gm₁m₂/r², where G is the gravitational constant." },
    { q: "Explain the difference between speed and velocity.", hint: "Scalar vs vector, direction.", idealAnswer: "Speed is the distance covered per unit time (a scalar, only magnitude) — e.g., 60 km/h. Velocity is the displacement per unit time (a vector, with direction) — e.g., 60 km/h towards north. A body can have constant speed but changing velocity (in circular motion)." },
    { q: "What is work, energy and power? Give their SI units.", hint: "W=Fd (Joule), Energy (Joule), Power=W/t (Watt).", idealAnswer: "Work is done when a force moves a body (W = F × d), SI unit Joule (J). Energy is the ability to do work, SI unit Joule (J). Power is the rate of doing work (P = W/t), SI unit Watt (W). 1 Watt = 1 Joule per second." },
    { q: "Describe the working of a simple electric circuit.", hint: "Cell, wires, switch, bulb, current flow.", idealAnswer: "A simple electric circuit has a power source (cell/battery), connecting wires, a switch, and a device (like a bulb). When the switch is closed, the circuit is complete and current flows from the positive terminal through the device back to the negative terminal, lighting the bulb. An open switch breaks the flow." },
    { q: "What is sound? How does it travel and why can't it travel in vacuum?", hint: "Mechanical wave, needs medium.", idealAnswer: "Sound is a form of energy produced by vibrating objects. It travels as a mechanical (longitudinal) wave through compressions and rarefactions in a medium (solid, liquid, or gas). It cannot travel through a vacuum because there are no particles to vibrate and carry the wave." },
    { q: "Explain reflection and refraction of light.", hint: "Bouncing back vs bending.", idealAnswer: "Reflection is the bouncing back of light when it strikes a surface — the angle of incidence equals the angle of reflection. Refraction is the bending of light as it passes from one medium to another (e.g., air to water) due to a change in its speed. This is why a straw looks bent in a glass of water." },
  ],
  Chemistry: [
    { q: "Explain the difference between exothermic and endothermic reactions with examples.", hint: "Heat released vs absorbed.", idealAnswer: "An exothermic reaction releases heat (temperature rises) — e.g., burning of fuel, respiration. An endothermic reaction absorbs heat (temperature falls) — e.g., photosynthesis, melting ice. In exothermic, products have less energy than reactants; in endothermic, more." },
    { q: "What is the periodic table? How are elements arranged in it?", hint: "Atomic number, periods, groups.", idealAnswer: "The periodic table arranges all known elements in order of increasing atomic number. Horizontal rows are periods (7) and vertical columns are groups (18). Elements in the same group have similar chemical properties due to the same number of valence electrons." },
    { q: "Define oxidation and reduction. Explain with an example.", hint: "Loss vs gain of electrons (OIL RIG).", idealAnswer: "Oxidation is loss of electrons (or gain of oxygen); reduction is gain of electrons (or loss of oxygen). 'OIL RIG' — Oxidation Is Loss, Reduction Is Gain. Example: 2Mg + O₂ → 2MgO, magnesium is oxidized, oxygen is reduced." },
    { q: "What is an atom? Describe its main subatomic particles.", hint: "Proton, neutron, electron.", idealAnswer: "An atom is the smallest particle of an element that retains its properties. It has three main subatomic particles: protons (positive, in nucleus), neutrons (neutral, in nucleus), and electrons (negative, orbiting the nucleus). Protons and neutrons give mass; electrons determine chemical behaviour." },
    { q: "Differentiate between an acid and a base with examples.", hint: "pH, litmus test.", idealAnswer: "An acid releases H⁺ ions in water, tastes sour, turns blue litmus red, pH below 7 — e.g., HCl, vinegar. A base releases OH⁻ ions, tastes bitter, turns red litmus blue, pH above 7 — e.g., NaOH, soap. When mixed, they neutralize to form salt and water." },
    { q: "What is a chemical bond? Explain ionic and covalent bonds.", hint: "Transfer vs sharing of electrons.", idealAnswer: "A chemical bond is the force that holds atoms together. An ionic bond forms by transfer of electrons between a metal and non-metal — e.g., NaCl. A covalent bond forms by sharing of electrons between non-metals — e.g., H₂O. Ionic compounds conduct electricity when molten; covalent usually don't." },
    { q: "Define a solution. What is the difference between solute and solvent?", hint: "Dissolved vs dissolving.", idealAnswer: "A solution is a homogeneous mixture of two or more substances. The solute is the substance that dissolves (smaller amount, e.g., sugar), and the solvent is the substance in which it dissolves (larger amount, e.g., water). Together they form a solution like sugar dissolved in water." },
    { q: "What is the difference between physical and chemical change? Give examples.", hint: "Reversible vs new substance.", idealAnswer: "A physical change alters appearance but not composition, and is usually reversible — e.g., melting ice, boiling water. A chemical change forms a new substance and is usually irreversible — e.g., burning paper, rusting iron. Chemical changes involve breaking and forming bonds." },
  ],
  Mathematics: [
    { q: "What is the quadratic formula? When is it used?", hint: "x = [-b ± √(b²-4ac)] / 2a", idealAnswer: "The quadratic formula is x = [-b ± √(b² - 4ac)] / 2a. It finds the roots of any quadratic equation ax² + bx + c = 0. The discriminant (b² - 4ac): positive = two real roots, zero = one root, negative = no real roots." },
    { q: "Define the Pythagoras theorem and state its formula.", hint: "Right-angled triangle, hypotenuse.", idealAnswer: "The Pythagoras theorem states that in a right-angled triangle, the square of the hypotenuse equals the sum of the squares of the other two sides: c² = a² + b², where c is the hypotenuse and a, b are the other sides." },
    { q: "Explain the difference between arithmetic and geometric sequences.", hint: "Common difference vs common ratio.", idealAnswer: "An arithmetic sequence has a constant difference (d) between terms — e.g., 2, 5, 8, 11 (d=3). A geometric sequence has a constant ratio (r) — e.g., 2, 6, 18, 54 (r=3). Arithmetic adds; geometric multiplies." },
    { q: "What is a matrix? Explain its order with an example.", hint: "Rows × columns arrangement.", idealAnswer: "A matrix is a rectangular arrangement of numbers in rows and columns. Its order is written as (rows × columns). For example, a matrix with 2 rows and 3 columns has order 2×3. Matrices are used to solve systems of equations and in transformations." },
    { q: "Define logarithm. State two basic laws of logarithms.", hint: "Inverse of exponent, product & quotient laws.", idealAnswer: "A logarithm is the power to which a base must be raised to get a number (if aˣ = n, then log_a n = x). Two laws: 1) Product law: log(mn) = log m + log n. 2) Quotient law: log(m/n) = log m - log n." },
    { q: "What are real numbers? Explain rational and irrational numbers.", hint: "Fractions vs non-terminating decimals.", idealAnswer: "Real numbers include all rational and irrational numbers. Rational numbers can be written as a fraction p/q (q≠0) — e.g., 1/2, 0.75, 5. Irrational numbers cannot be written as a simple fraction and have non-terminating, non-repeating decimals — e.g., π, √2." },
    { q: "Explain how to factorize a quadratic expression with an example.", hint: "Split the middle term.", idealAnswer: "To factorize ax² + bx + c, split the middle term into two parts whose product is (a×c) and sum is b. Example: x² + 5x + 6 → x² + 2x + 3x + 6 → x(x+2) + 3(x+2) → (x+2)(x+3). Factorization helps solve equations." },
    { q: "What is trigonometry? Define sine, cosine, and tangent ratios.", hint: "Right triangle side ratios.", idealAnswer: "Trigonometry studies relationships between angles and sides of triangles. In a right triangle: sine (sin) = opposite/hypotenuse, cosine (cos) = adjacent/hypotenuse, tangent (tan) = opposite/adjacent. Remember 'SOH-CAH-TOA'." },
  ],
  Biology: [
    { q: "Explain enzyme action using Lock and Key vs Induced Fit model.", hint: "Rigid vs flexible active site.", idealAnswer: "The Lock and Key model (Fischer) says the enzyme's active site is rigid and exactly fits the substrate like a key in a lock. The Induced Fit model (Koshland) says the active site is flexible and changes shape when the substrate binds for a better fit. Both explain enzyme specificity." },
    { q: "Differentiate between mitosis and meiosis.", hint: "Growth (2 cells) vs gametes (4 cells).", idealAnswer: "Mitosis produces two genetically identical diploid cells for growth and repair. Meiosis produces four genetically different haploid cells (gametes) for reproduction. Mitosis has one division; meiosis has two divisions with crossing over for variation." },
    { q: "Describe the process of photosynthesis with its equation.", hint: "Sunlight, chlorophyll, glucose, oxygen.", idealAnswer: "Photosynthesis is how green plants make food (glucose) using sunlight, water, and CO₂ with chlorophyll, in chloroplasts. Equation: 6CO₂ + 6H₂O → (sunlight, chlorophyll) → C₆H₁₂O₆ + 6O₂. Oxygen is released as a by-product." },
    { q: "What is a cell? Describe the main parts of an animal cell.", hint: "Membrane, cytoplasm, nucleus, organelles.", idealAnswer: "A cell is the basic structural and functional unit of life. An animal cell has: cell membrane (controls entry/exit), cytoplasm (jelly-like fluid with organelles), nucleus (controls activities, contains DNA), mitochondria (energy), ribosomes (protein synthesis), and others." },
    { q: "Explain the human digestive system briefly.", hint: "Mouth → stomach → intestines → absorption.", idealAnswer: "The digestive system breaks food into nutrients. Food enters the mouth (chewing, saliva), passes through the esophagus to the stomach (acid and enzymes), then to the small intestine (digestion completes, nutrients absorbed), and finally the large intestine (water absorbed, waste removed)." },
    { q: "What is respiration? Differentiate between aerobic and anaerobic respiration.", hint: "With vs without oxygen.", idealAnswer: "Respiration is the breakdown of glucose to release energy (ATP). Aerobic respiration uses oxygen, releasing more energy + CO₂ + water (in most cells). Anaerobic respiration occurs without oxygen, releasing less energy + lactic acid (in muscles) or alcohol + CO₂ (in yeast)." },
    { q: "Describe the structure and function of the human heart.", hint: "Four chambers, pumps blood.", idealAnswer: "The heart is a muscular organ that pumps blood. It has four chambers: two upper atria (receive blood) and two lower ventricles (pump blood out). The right side pumps deoxygenated blood to the lungs; the left side pumps oxygenated blood to the body. Valves prevent backflow." },
    { q: "What is genetics? Explain the terms gene, DNA, and chromosome.", hint: "Heredity, units of inheritance.", idealAnswer: "Genetics is the study of heredity (how traits pass from parents to offspring). A gene is a unit of inheritance that codes for a trait. DNA is the molecule that carries genetic information. A chromosome is a thread-like structure of coiled DNA; humans have 23 pairs (46 total)." },
  ],
  English: [
    { q: "What is the difference between active and passive voice? Give examples.", hint: "Subject does vs receives action.", idealAnswer: "In active voice, the subject performs the action — e.g., 'Ali wrote a letter.' In passive voice, the subject receives the action — e.g., 'A letter was written by Ali.' Active is direct; passive emphasizes the action or object." },
    { q: "Explain the rules for changing direct speech into indirect speech.", hint: "Tense back-shift, pronouns, time words.", idealAnswer: "1) The reporting verb may change (said → told). 2) Tense shifts back (present → past). 3) Pronouns change according to the subject. 4) Time/place words change (now → then, here → there). Example: He said, 'I am happy' → He said that he was happy." },
    { q: "What are the parts of speech? Name them with one example each.", hint: "Noun, verb, adjective, etc.", idealAnswer: "There are eight parts of speech: Noun (Ali, book), Pronoun (he, she), Verb (run, eat), Adjective (beautiful, tall), Adverb (quickly, very), Preposition (in, on), Conjunction (and, but), and Interjection (Oh! Wow!)." },
    { q: "Write a short note on the importance of education.", hint: "Knowledge, progress, character.", idealAnswer: "Education is the backbone of a nation's progress. It develops knowledge, skills, and good character. An educated person can think critically, earn a respectable living, and contribute to society. Education removes ignorance, promotes equality, and is essential for the development of any country like Pakistan." },
    { q: "Explain the difference between a phrase and a clause.", hint: "No verb vs has verb.", idealAnswer: "A phrase is a group of related words without a subject and verb — e.g., 'on the table', 'a tall boy'. A clause is a group of words that contains a subject and a verb — e.g., 'he is reading'. A clause can express a complete thought; a phrase cannot." },
    { q: "What is a tense? Name the three main tenses with examples.", hint: "Time of action.", idealAnswer: "A tense shows the time of an action. The three main tenses are: Present (I write / I am writing), Past (I wrote / I was writing), and Future (I will write / I shall write). Each has four forms: simple, continuous, perfect, and perfect continuous." },
  ],
  Urdu: [
    { q: "علامہ اقبال کے کلام کی خصوصیات بیان کریں۔", hint: "خودی، عشقِ رسول، فلسفہ، پیغامِ عمل۔", idealAnswer: "علامہ اقبال کے کلام کی نمایاں خصوصیات میں فلسفہٴ خودی، عشقِ رسول ﷺ، نوجوانوں کو عمل کی دعوت، اتحادِ امت، اور مشرقی و اسلامی تہذیب کا فروغ شامل ہیں۔ ان کا کلام فکر انگیز، پُرجوش اور بلند آہنگ ہے۔" },
    { q: "اسمِ نکرہ اور اسمِ معرفہ میں فرق واضح کریں۔", hint: "عام نام بمقابلہ خاص نام۔", idealAnswer: "اسمِ نکرہ وہ اسم ہے جو کسی عام چیز یا شخص کے لیے ہو، جیسے: لڑکا، شہر، کتاب۔ اسمِ معرفہ وہ اسم ہے جو کسی خاص چیز کے لیے ہو، جیسے: علی، لاہور، قرآن۔ نکرہ غیر معین، معرفہ معین ہوتا ہے۔" },
    { q: "محاورہ اور ضرب المثل میں کیا فرق ہے؟ مثالیں دیں۔", hint: "جملے کا حصہ بمقابلہ مکمل حکمت۔", idealAnswer: "محاورہ ایسا جملہ یا فقرہ ہے جو اپنے لغوی معنی کے بجائے مجازی معنی دیتا ہے، جیسے: 'آنکھیں چرانا'۔ ضرب المثل ایک مکمل بامحاورہ جملہ ہوتا ہے جو کسی تجربے یا حکمت پر مبنی ہو، جیسے: 'ناچ نہ جانے آنگن ٹیڑھا'۔" },
    { q: "خط نویسی کے بنیادی اصول بیان کریں۔", hint: "عنوان، آداب، مضمون، اختتام۔", idealAnswer: "خط نویسی کے اصول: 1) اوپر تاریخ اور پتہ لکھیں۔ 2) مناسب آداب (محترم/پیارے) سے آغاز کریں۔ 3) مضمون واضح اور مختصر ہو۔ 4) موضوع کے مطابق بات کریں۔ 5) آخر میں مناسب الفاظ (آپ کا مخلص) اور نام لکھیں۔" },
    { q: "نظم اور غزل میں فرق واضح کریں۔", hint: "ایک موضوع بمقابلہ الگ اشعار۔", idealAnswer: "نظم میں تمام اشعار ایک ہی موضوع یا خیال کے گرد ہوتے ہیں اور ربط رکھتے ہیں۔ غزل میں ہر شعر اپنا الگ مضمون رکھتا ہے اور مستقل ہوتا ہے۔ غزل میں ردیف و قافیہ کی پابندی ہوتی ہے جبکہ نظم میں موضوع کا تسلسل اہم ہے۔" },
  ],
  "Pak Studies": [
    { q: "What is the constitutional role of the Senate in Pakistan's Parliament?", hint: "Upper house, equal provincial representation.", idealAnswer: "The Senate is the upper house of Pakistan's bicameral Parliament, established under the 1973 Constitution. It ensures equal representation for all four provinces, balancing the population-based National Assembly. It passes legislation, approves amendments, and protects provincial rights." },
    { q: "Explain the importance of the Two-Nation Theory.", hint: "Muslims & Hindus separate nations.", idealAnswer: "The Two-Nation Theory states that Muslims and Hindus are two distinct nations with different religions, cultures, and ways of life, so they cannot live as one nation. Championed by Sir Syed and Iqbal, and realized by Quaid-e-Azam, it became the ideological basis for Pakistan's creation in 1947." },
    { q: "Describe the natural resources of Pakistan.", hint: "Minerals, agriculture, water, gas.", idealAnswer: "Pakistan is rich in natural resources: agricultural land (wheat, cotton, rice), minerals (coal, copper, gold at Saindak/Reko Diq), natural gas (Sui), water resources (rivers, dams like Tarbela and Mangla), and salt (Khewra). These resources are vital for the country's economy." },
    { q: "What were the main objectives of the Pakistan Movement?", hint: "Separate homeland, Muslim rights.", idealAnswer: "The main objectives were: 1) A separate homeland for Muslims of the subcontinent. 2) Protection of Muslim religious, cultural, and political rights. 3) Freedom from both British and Hindu domination. 4) The right to live according to Islamic principles. The Lahore Resolution (1940) formalized these aims." },
    { q: "Explain the geographical importance of Pakistan.", hint: "Location, neighbours, trade routes.", idealAnswer: "Pakistan has a strategic location in South Asia. It borders India, Afghanistan, Iran, and China, with the Arabian Sea to the south. It connects Central Asia, the Middle East, and South Asia. Gwadar Port and CPEC make it a key trade and energy corridor, boosting its regional importance." },
  ],
};

// Subject icons (UI ke liye)
export const QA_ICONS: Record<string, string> = {
  Physics: "⚛️",
  Chemistry: "🧪",
  Mathematics: "📐",
  Biology: "🧬",
  English: "✍️",
  Urdu: "📜",
  "Pak Studies": "🇵🇰",
};
